# Usando uma imagem base do Python
FROM python:3.9

# Instalando o cliente PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client
RUN sudo apt-get install libpq-dev

# Definindo o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiando o arquivo requirements.txt para o diretório de trabalho
COPY requirements.txt .

# Instalando as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiando todos os arquivos do diretório atual para o diretório de trabalho
COPY . .

# Configurando variáveis de ambiente para a conexão com o banco de dados
ENV POSTGRES_HOST=db
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=library_db
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Executando os comandos para criar e migrar o banco de dados
RUN python manage.py makemigrations
RUN python manage.py migrate

# Expondo a porta necessária para o servidor Django
EXPOSE 8000

# Iniciando o servidor Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
