name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v1
        with:
          compose-file: docker-compose.yml

      - name: Build and test
        run: |
          docker-compose build
          docker-compose run backend python manage.py test

      - name: Deploy
        run: |
          docker-compose up -d
