name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: compose
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ".docker-compose.yml"
          down-flags: "--volumes"
          services: |
            db
            backend
            frontend
            nginx

      - name: Deploy
        run: |
          docker-compose up -d
