name: Test Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.4-alpine
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: Wait for containers to start
        run: sleep 10

      - name: Run tests
        run: |
          docker-compose exec backend python manage.py test

      - name: Stop containers
        run: docker-compose down
